### ISSUE TITLE
Mac OSX Mojave

### ISSUE THREAD

**Issue by Tadaboody** [JoshuaManuel/RoA_on_Mac#1]

**Comment by Tadaboody** [comment]
What version of OSX were you running when you made this? I'm running mojave and wineskin doesn't want to open my steam installer

**Comment by JoshuaManuel** [comment]
Hey Tadaboody, I'm using Sierra. I heard that High Sierra broke Wine for some people, so I never updated it.

**Comment by Tadaboody** [comment]
You probably heard right then because I can't make it work :/
